### ISSUE TITLE
Exception when opening PrimerExample in OWLEditor

### ISSUE THREAD

**Issue by jreimone** [komma/komma#3]
Tried to open the example from https://www.w3.org/2007/OWL/wiki/PrimerExampleTurtle which results in 

net.enilink.komma.core.KommaException: Invalid RDF data:
Unexpected end of file

	at net.enilink.komma.model.ModelUtil.readData(ModelUtil.java:648)

	at net.enilink.komma.model.sesame.SerializableModelSupport$1.run(SerializableModelSupport.java:211)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)

      Caused by: org.openrdf.rio.RDFParseException: Unexpected end of file

	at org.openrdf.rio.turtle.TurtleParser.throwEOFException(TurtleParser.java:1422)

	at org.openrdf.rio.turtle.TurtleParser.verifyCharacterOrFail(TurtleParser.java:1207)

	at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:261)

	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:214)

	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:158)

	at net.enilink.komma.model.ModelUtil.readData(ModelUtil.java:646)

	... 4 more

**Comment by jreimone** [comment]
Pasted example without dot at the end
